import "./globals.css";
import type { Metadata } from "next";
import { 
  LayoutProvider 
} from "@/components/provider";
import { 
  Footer, 
  Header 
} from "@/components/common";

export const metadata: Metadata = {
  title: "Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <LayoutProvider>
        <Header/>
        {children}
        <Footer/>
      </LayoutProvider>
  );
}
